pipelines:
  - name: inline_pipeline_00012
    steps:
      - name: inline_p0001_step_0012
        type: Bash
        execution:
          onExecute:
            - echo {{ .Values.GitRepo.gitProvider }}
